import Navbar from '../components/Navbar'
import '../styles/globals.css'
import Head from 'next/head'
import Script from 'next/script'
import Footer from '../components/Footer'
import { apiStore } from './../redux/apiStore'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import { persistStore } from 'redux-persist'

let persistor = persistStore(apiStore)

function MyApp ({ Component, pageProps }) {
  const Layout = Component.Layout || EmptyLayout
  return (
    <>
      <Provider store={apiStore}>
        <PersistGate loading={null} persistor={persistor}>
          <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
            <link
              href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css'
              rel='stylesheet'
              integrity='sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC'
              crossorigin='anonymous'
            ></link>
          </Head>
          <Script
            src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'
            integrity='sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM'
            crossorigin='anonymous'
          />
          <Navbar />
          <Layout>
            <Component {...pageProps} />
          </Layout>
          <Footer />
        </PersistGate>
      </Provider>
    </>
  )
}
const EmptyLayout = ({ children }) => <>{children}</>

export default MyApp
